### ISSUE TITLE
Update to Bevy 0.10

### ISSUE THREAD

**Issue by naomijub** [Game4all/vx_bevy#16]
https://bevyengine.org/learn/migration-guides/0.9-0.10/ 

Cargo outdated -R shows:
```sh
Name             Project  Compat  Latest  Kind    Platform
----             -------  ------  ------  ----    --------
bevy             0.9.1    ---     0.10.0  Normal  ---
bevy_atmosphere  0.5.0    ---     0.6.0   Normal  ---
bevy_egui        0.17.1   ---     0.20.2  Normal  ---
bitflags         1.3.2    ---     2.0.2   Normal  ---
once_cell        1.16.0   1.17.1  1.17.1  Normal  ---
thread_local     1.1.4    1.1.7   1.1.7   Normal  ---
```

The following crates can be updated without any problems:
```toml
thread_local = "1.1.7"
once_cell = "1.17.1"
simdnoise = "3.1.6"
bitflags = "2.0.2"
```
